services:
  - type: pserv
    name: listmonk-db
    env: postgres
    plan: free
    region: oregon
    envVars:
      - key: POSTGRES_DB
        value: listmonk
      - key: POSTGRES_USER
        value: listmonk
      - key: POSTGRES_PASSWORD
        value: changeme123

  - type: web
    name: listmonk
    env: docker
    repo: https://github.com/codebloq/listmonk
    region: oregon
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    buildCommand: ./listmonk --install --yes
    envVars:
      - key: LISTMONK_app__admin_username
        value: admin
      - key: LISTMONK_app__admin_password
        value: changeme123
      - key: LISTMONK_db__host
        fromService:
          type: pserv
          name: listmonk-db
          property: host
      - key: LISTMONK_db__port
        fromService:
          type: pserv
          name: listmonk-db
          property: port
      - key: LISTMONK_db__user
        value: listmonk
      - key: LISTMONK_db__password
        value: changeme123
      - key: LISTMONK_db__database
        value: listmonk
