services:
  - type: web
    name: listmonk
    env: docker
    repo: https://github.com/codebloq/listmonk
    region: singapore
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    buildCommand: ./listmonk --install --yes
    envVars:
      - key: LISTMONK_app__admin_username
        value: admin
      - key: LISTMONK_app__admin_password
        value: changeme123
      - key: LISTMONK_db__host
        fromService:
          type: database
          name: listmonk-db
          property: host
      - key: LISTMONK_db__port
        fromService:
          type: database
          name: listmonk-db
          property: port
      - key: LISTMONK_db__user
        fromService:
          type: database
          name: listmonk-db
          property: user
      - key: LISTMONK_db__password
        fromService:
          type: database
          name: listmonk-db
          property: password
      - key: LISTMONK_db__database
        fromService:
          type: database
          name: listmonk-db
          property: database
